### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by WhiteBoardDev** [WhiteBoardDev/address-location-tool#8]
[evanharris@Evans-MacBook-Pro src (master ✗)]$ python app.py alt 
ERROR:root:mac unsupported

**Comment by cnishina** [comment]
as designed until the configuration is completed in common/settings.py. depends on installation script.

```
linux = {
    'base_dir': '/opt/alt',
    'conf_dir': '/etc/alt/conf',
    'log_conf': '/var/log/',
    'hosts_file': '/etc/hosts'
}

darwin = {}

windows = {}
```

**Comment by cnishina** [comment]
updating issue #7 for alt support. this depends on installation script / bat file.
